POST http://localhost:5000/api/event
Content-Type: application/json

{
    "title":"this is the second item",
    "startDate":"2023-02-01 05:00:00",
    "finishDate":"2023-02-01 08:00:00",
    "createdAt":"2023-02-01 09:00:00"

}
###
GET  http://localhost:5000/api/events
Content-Type: application/json

###

PUT http://localhost:5500/api/item/63df1dd16b637076884819c1
Content-Type: application/json

{
    "item":"this is the firs item but updated !!",
    "completed":true
}


###

DELETE http://localhost:5500/api/item/63df1dd16b637076884819c1
Content-Type: application/json


